# Generated by Django 2.1 on 2018-08-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='long',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='short',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
